### ISSUE TITLE
git semaphore going wrong

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/TOSBack-CGUs-bridge#17]
```sh
root@ubuntu-s-8vcpu-16gb-nyc1-01:~/TOSBack-CGUs-bridge# ONLY=whatsapp.com sh run-trial.sh 
nvm
Switched to branch 'all-file-paths'
Your branch is up to date with 'me/all-file-paths'.
Already up to date.
1711
HEAD is now at c02f4f9f18a Add readme and license
HEAD is now at 05d4c3e43 Add Readme and License
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Filtering filenames for importCrawls, looking for whatsapp.com
crawl_reviewed/whatsapp.com/Terms of Service and Privacy (EU).txt bomb Unsupported type: Terms of Service and Privacy (EU)
crawl_reviewed/whatsapp.com/Terms of Service and Privacy.txt WhatsApp Terms of Service fail Same type used twice!
crawl_reviewed/whatsapp.com/Terms of Service and Privacy.txt bomb snapshot10Git is not defined
/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60
        const gitError = (e instanceof api_1.GitError) ? Object.assign(e, { task }) : new api_1.GitError(task, e && String(e));
                                                                                      ^

GitError: fatal: Unable to create '/root/tosback2/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

    at GitExecutorChain.onFatalException (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  task: {
    commands: [ 'checkout', 'all-file-paths' ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
root@ubuntu-s-8vcpu-16gb-nyc1-01:~/TOSBack-CGUs-bridge#

**Comment by michielbdejong** [comment]
Fixed in 3814374
