### ISSUE TITLE
importing history of docs that no longer exist in tosback2

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/TOSBack-CGUs-bridge#7]
I added code that finds docs that have existed in the past, but I can't check out their history due to this error:
```sh
/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60
        const gitError = (e instanceof api_1.GitError) ? Object.assign(e, { task }) : new api_1.GitError(task, e && String(e));
                                                                                      ^

GitError: fatal: ambiguous argument 'crawl_reviewed/123greetings.com/Privacy Policy.txt': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at GitExecutorChain.onFatalException (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/root/TOSBack-CGUs-bridge/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  task: {
    concatStdErr: false,
    onError: undefined,
    format: 'utf-8',
    parser: [Function (anonymous)],
    commands: [
      'log',
      '--pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %ae òò',
      '--follow',
      'crawl_reviewed/123greetings.com/Privacy Policy.txt'
    ]
  }
}
Total 0 (delta 0), reused 0 (delta 0)

**Comment by michielbdejong** [comment]
```sh
cat ../TOSBack-CGUs-bridge/crawl-files-list.txt | awk '{print "mkdir -p \"" $0 "\"; touch \"" $0 "\"" }' | sh
ls -l crawl*/*/*.txt | wc -l
3947
```

**Comment by michielbdejong** [comment]
ah, the problem is 'crawl/123greetings.com/Privacy Policy.txt' exists but 'crawl_reviewed/123greetings.com/Privacy Policy.txt' doesn't.

**Comment by michielbdejong** [comment]
Correction:
```sh
cat ../TOSBack-CGUs-bridge/crawl-files-list.txt | awk -F'/' '{print "mkdir \"" $1 "/" $2 "\"; touch \"" $0 "\"" }' | head

**Comment by michielbdejong** [comment]
This is working now, thanks to https://github.com/ambanum/TOSBack-CGUs-bridge/blob/0d5997b/tosback-import.js#L37
